import type { Feedback } from './types';

export const feedbacks: Feedback[] = [
  {
    id: 1,
    message: "The doctor was amazing, so attentive and explained everything clearly. The hospital was clean, but the nurse seemed a bit rushed.",
    doctor_score: 9,
    nurse_score: 6,
    hospital_score: 8,
    notes_analysis: "The patient had a very positive experience with the doctor, highlighting their attentiveness and clear communication. The hospital environment was also viewed favorably. The nurse's score was lower due to the patient perceiving them as rushed.",
    created_at: "2024-07-28T10:00:00Z",
  },
  {
    id: 2,
    message: "Everything was top-notch. From the moment I walked in, the staff at the hospital were friendly, the nurse was compassionate, and the doctor was a true professional. Couldn't ask for more.",
    doctor_score: 10,
    nurse_score: 10,
    hospital_score: 10,
    notes_analysis: "This is an overwhelmingly positive feedback. The patient gave perfect scores across the board, emphasizing professionalism, friendliness, and compassion from all parties involved.",
    created_at: "2024-07-28T11:30:00Z",
  },
  {
    id: 3,
    message: "The hospital felt a bit dated and could use a renovation. The medical care was okay, my doctor was knowledgeable but had a poor bedside manner. The nurse was the highlight, very caring.",
    doctor_score: 6,
    nurse_score: 9,
    hospital_score: 4,
    notes_analysis: "The patient's feedback is mixed. They were very satisfied with the nursing care. However, the physical condition of the hospital and the doctor's bedside manner were points of dissatisfaction.",
    created_at: "2024-07-27T15:45:00Z",
  },
  {
    id: 4,
    message: "My stay was alright. The check-in process at the hospital was slow. The doctor did a good job with the treatment.",
    doctor_score: 8,
    nurse_score: 5,
    hospital_score: 6,
    notes_analysis: "The patient's feedback is neutral to positive. The doctor's treatment was appreciated. The hospital's administrative process (check-in) was a negative point. The nurse was not mentioned, resulting in a neutral score.",
    created_at: "2024-07-27T09:12:00Z",
  },
  {
    id: 5,
    message: "Terrible experience. The hospital was noisy and I could not get any rest. The doctor dismissed my concerns, and I barely saw my nurse.",
    doctor_score: 2,
    nurse_score: 3,
    hospital_score: 2,
    notes_analysis: "This feedback indicates a very poor patient experience. The patient felt their concerns were not heard by the doctor, the nursing presence was minimal, and the hospital environment was not conducive to recovery.",
    created_at: "2024-07-26T20:05:00Z",
  },
  {
    id: 6,
    message: "The nurse who took care of me was an angel. So patient and kind. The hospital facilities were excellent.",
    doctor_score: 5,
    nurse_score: 10,
    hospital_score: 9,
    notes_analysis: "The feedback is very positive about the nurse and hospital facilities. The doctor was not mentioned, hence the neutral score. The patient's experience was heavily influenced by the high quality of nursing care.",
    created_at: "2024-07-26T14:20:00Z",
  },
   {
    id: 7,
    message: "Dr. Smith was fantastic, but the billing department at the hospital is a nightmare. It took weeks to sort out a simple error.",
    doctor_score: 9,
    nurse_score: 5,
    hospital_score: 3,
    notes_analysis: "The patient clearly distinguishes between the quality of medical care and administrative processes. High praise for the doctor is contrasted with significant frustration with the hospital's billing department.",
    created_at: "2024-07-25T18:00:00Z",
  }
];
